### ISSUE TITLE
Nextcloud 21

### ISSUE THREAD

**Issue by sunjam** [alexstocker/sensorlogger#100]
Please add support.  Thanks!

**Comment by e-alfred** [comment]
@alexstocker Could you add support for Nextcloud 21 and PHP 7.4 to Sensorlogger? That would be awesome!

**Comment by stefan123t** [comment]
Already included on latest master branch in [info.xml](https://github.com/alexstocker/sensorlogger/blob/master/appinfo/info.xml#L45-L47). Can be closed as resolved.

**Comment by tflidd** [comment]
The version wasn't released on https://apps.nextcloud.com/apps/sensorlogger.

Would be great to add support for versions up to NC24
