### ISSUE TITLE
Nextcloud 22 and "The appinfo/database.xml file is not longer supported. Used in sensorlogger" error

### ISSUE THREAD

**Issue by stefan123t** [alexstocker/sensorlogger#103]
**Describe the bug**
Upgraded to Nextcloud 22.1.4 with success.
Now sensorlogger has been disabled during upgrade
I have enabled it again but it displays error:
 The appinfo/database.xml file is not longer supported. Used in sensorlogger 

**To Reproduce**
1. Go to 'Admin > Apps > Disabled Apps'
2. Click on 'Enable'
3. See error
 The appinfo/database.xml file is not longer supported. Used in sensorlogger 

**Expected behavior**
Should enable the sensorlogger again.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11159753/134816150-81bac7e2-2421-4aae-913d-16b5eaa4786e.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2
 - Browser Firefox 90.1
 - Version 22.1.4
 - sensorlogger 0.0.9

**Additional context**
I have seen that according to the changes in #100 the nextcloud max version is set to 23.
MySQL / Maria DB Version is:
mysql --version
mysql  Ver 15.1 Distrib 10.5.10-MariaDB, for Linux (x86_64) using readline 8.1
PHP is version 7.4

**Comment by stefan123t** [comment]
@alexstocker many thanks for your plugin times and again.

Given the changes between master and 0.1-nc-devel I have seen that appinfo/database.xml has already been removed from the sensorlogger code tree.
It could be that I still have the old stale file around and that this preventing upgrade from my current 0.0.9 -> 0.1.4 version now.

Should this be solved by removing it manually or do you plan on providing a smooth upgrade path by removing this file in a pre-install step somehow, then I would wait for you to test this once it is released / committed ?

Kind regards,
Stefan

**Comment by stefan123t** [comment]
According to the old Nextcloud 21 documentation https://docs.nextcloud.com/server/21/developer_manual/basics/storage/migrations.html#migrate-from-database-xml I should call the following to create the respective table layouts under lib/Migration. Unfortunately I am already past the upgrade to NC22. If you want I can try to roll back to NC21 to try it again. I just did the upgrade yesterday.

php occ migrations:generate-from-schema sensorlogger 000009
The current PHP memory limit is below the recommended value of 512MB.
  There are no commands defined in the "migrations" namespace.

**Comment by stefan123t** [comment]
In NC22 the migrations has been disabled and is only available in Debug mode, should I try to enable Debug mode for sensorlogger ?

https://docs.nextcloud.com/server/22/developer_manual/app_publishing_maintenance/upgrade-guide.html#migration-commands

**Comment by stefan123t** [comment]
The appinfo/database.xml has to be removed and the app has to supply its lib/Migration/ scripts to upgrade the database schema between versions. See https://github.com/owncloud/music/issues/865 for a sample in the music plugin and especially the commit https://github.com/owncloud/music/commit/6982d91b426785ca8679682bf52cdfcd8c00e32a

According to https://github.com/nextcloud/server/pull/27113 the migration command should only be used on developer env.

@alexstocker could you supply the relevant lib/Migration/Version000104Date20210927083000.php or similar upgrade script to create / modify the schema ?

**Comment by alexstocker** [comment]
@stefan123t Thanx for reporting. I'll do my best. But to be honest, will take a while. Any contributions are warmly welcome ;-)

**Comment by stefan123t** [comment]
Dear @alexstocker,

I have taken a quick, first stab at the necessary changes to make it show some of the old data under my Nextcloud 22.1:
![image](https://user-images.githubusercontent.com/11159753/138011540-17cecbcf-269b-499e-a0d0-755a5862a4a3.png)

[sensorlogger-0.1.4_nc22_patch.zip](https://github.com/alexstocker/sensorlogger/files/7377446/sensorlogger-0.1.4_nc22_patch.zip)

Here is the list of changes I made:

* lib/Migration/Version011400Date20211020010104.php

I have tried to incorporate all the suggested changes from appinfo/Migrations/Version*.php and these in their original form.
I do not know whether they should be placed into appinfo/Migrations as these two automagically generated ones (?) or under lib/Migration/Version*.php as suggested by @paulijar in owncloud/music@6982d91
I also did not yet remove the appinfo/database.xml just moved it somewhere else for Nextcloud 22.1 not to complain.

* lib/App.php -> added constructor with all six arguments from apps/files/lib/App.php to prevent the obvious constructor mismatch

`Exception: Too few arguments to function OC\NavigationManager::__construct(), 0 passed in .../apps/sensorlogger/lib/App.php on line 33 and exactly 6 expected`

```
         public static function getNavigationManager() {
                // TODO: move this into a service in the Application class
                if (self::$navigationManager === null) {
                        self::$navigationManager = new \OC\NavigationManager(
                                \OC::$server->getAppManager(),
                                \OC::$server->getURLGenerator(),
                                \OC::$server->getL10NFactory(),
                                \OC::$server->getUserSession(),
                                \OC::$server->getGroupManager(),
                                \OC::$server->getConfig()
                        );
                        self::$navigationManager->clear(false);
                }
                return self::$navigationManager;
        }
```

* lib/Devices.php -> I had to remove the ->select('*') in line 27 to prevent Doctrine execute error in line 40.
```
Doctrine\DBAL\Query\QueryException: Query is selecting * and specific values in the same query. This is not supported in Oracle.
    .../apps/sensorlogger/lib/Devices.php - line 40:
    OC\DB\QueryBuilder\QueryBuilder->execute()
```

```
	public static function getDevices($userId, IDBConnection $db) {
		$query = $db->getQueryBuilder();
		$query
			->selectAlias('sd.user_id','user_id')
			->selectAlias('sd.id','id')
			->selectAlias('sdt.device_type_name','device_type_name')
			->selectAlias('sdg0.device_group_name','device_group_name')
			->selectAlias('sdg1.device_group_name','device_group_parent_name')
			->from('sensorlogger_devices','sd')
			->leftJoin('sd', 'sensorlogger_device_types', 'sdt', 'sdt.id = sd.type_id')
			->leftJoin('sd', 'sensorlogger_device_groups', 'sdg0', 'sdg0.id = sd.group_id')
			->leftJoin('sd', 'sensorlogger_device_groups', 'sdg1', 'sdg1.id = sd.group_parent_id')
			->where('sd.user_id = "'.$userId.'"')
			->orderBy('sd.id', 'DESC');
		$query->setMaxResults(100);
		$result = $query->execute();
```

The query returns something like if I am not mistaken, maybe the * can simply be omitted or instead it may be specified explicitly which fields are required:
```
SELECT
    *,
    sd.user_id AS user_id,
    sd.id AS id,
    sdt.device_type_name AS device_type_name,
    sdg0.device_group_name AS device_group_name,
    sdg1.device_group_name AS device_group_parent_name
FROM
    nc_6613_sensorlogger_devices sd
LEFT JOIN nc_6613_sensorlogger_device_types sdt ON
    sdt.id = sd.type_id
LEFT JOIN nc_6613_sensorlogger_device_groups sdg0 ON
    sdg0.id = sd.group_id
LEFT JOIN nc_6613_sensorlogger_device_groups sdg1 ON
    sdg1.id = sd.group_parent_id
WHERE
    sd.user_id = 'userid'
ORDER BY
    sd.id
DESC
```

* appinfo/info.xml -> applied the changes you already made for #100 in https://github.com/alexstocker/sensorlogger/commit/2c072b3fd992492d4dca03a1339a9abcfc6ff94b 

I do not know why they were not in my sensorlogger-master.zip I downloaded to the server from GitHub.

**Comment by stefan123t** [comment]
@alexstocker thanks for adding the suggested changes to your 0.1.4 branch. I do not know if I am able to test / provoke this again e.g. by rolling back to 0.1.x and doing another upgrade. Hence I suggest to close this issue as resolved. I just checked and now even the graph seems to display fine. Thanks for this christmas present!
