### ISSUE TITLE
Timeout while createlog

### ISSUE THREAD

**Issue by escoand** [alexstocker/sensorlogger#23]
I tried SensorLogger in combination with OwnTracks and constantly receiving timeouts.

With curl on the command line it needs 70secs to respond to the request:
```
$ time curl -H 'Content-Type: application/json' -d '{"deviceId":"test"}' --user USER:PASSWD https://example.com/index.php/apps/sensorlogger/api/v1/createlog/
{"message":"CORS requires basic auth"}
real	1m10,438s
user	0m0,032s
sys	0m0,012s
```

This is not happening on normal http requests.

**Comment by alexstocker** [comment]
Thanx for your report. I have never tested this combination but I will have a look and let you know.

**Comment by escoand** [comment]
Seems to be a generic problem. 70 seconds for this short curl test is too much in my opinion.
How can I debug this?

**Comment by alexstocker** [comment]
It's not just an generic problem as there are no "3rd party data providers" implemented . I'm planning to add an interface to add data from 3rd party sources based on there API. 
Starting with OwnTracks sounds interesting to me.
