### ISSUE TITLE
Arduino support

### ISSUE THREAD

**Issue by FilipK-CZ** [alexstocker/sensorlogger#24]
Is Arduino (or NodeMCU) supported?

**Comment by alexstocker** [comment]
Probably, if you get somthing like [https://github.com/NorthernMan54/nodemcu-dht-yl69-json-mdns](https://github.com/NorthernMan54/nodemcu-dht-yl69-json-mdns) to send a json like [this](https://github.com/alexstocker/sensorlogger/wiki/API-Calls)
If you find a solution, please let me know.

**Comment by e-alfred** [comment]
Seems to be solved by this comment: https://github.com/alexstocker/sensorlogger/issues/33#issuecomment-340618118

**Comment by nekromant** [comment]
@gamecraft45 I'm writing a generic esp8266 sensorlogger library here: https://github.com/nekromant/esp8266-frankenstein
but it's not yet ready for everyday use
