### ISSUE TITLE
Own dataTypes

### ISSUE THREAD

**Issue by CodeUnit** [alexstocker/sensorlogger#25]
I can't create my own dataTypes like fan speed.

My API call for 'registerdevice':
```	 
"_route":"sensorlogger.apisensorlogger.registerDevice",
"deviceId":"231d2508-786d-400d",
"deviceName":"PC Sensoren",
"deviceType": "CPU Temp u. Fan speed",
"deviceGroup": "Wohnzimmer",
"deviceParentGroup": "Server",
"deviceDataTypes": 
[
    {
	"type": "temp",
	"description": "Temperature",
	"unit": "°C"
    }
    ,
    {
	"type": "fan1",
	"description": "Fan1",
	"unit": "U/min"
    }
]

```
My API call for 'createlog':
```
$fan = 100;
$cpu = 1000;
$array = array("deviceId" => "231d2508-786d-400d",
	"temp" => $cpu,
	"fan1" => $fan,
	"date" => date('Y-m-d H:i:s'));
$data_json = json_encode($array);
```
But in NextCloud I only see at 'List':
```
#  UUID               °C     % r.F. Created
1  231d2508-786d-400d  0.00  0.00   2017-05-12 08:22:23
```

**Comment by alexstocker** [comment]
Your are almost there!

1) After you registered a device you have to get "dataTypeIds" from the database via api call [getdevicedatatypes](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#getdevicedatatypes) (or you just have a look @ "Data Types" in the menu)

2) To log your data use the [extended](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#extended) createlog api call

3) to view "extended" log data with self defined data types you have two options

- show Chart
- add dashboard widget "Data List" (shows last 10 records)

working demo: [https://mycloud.html5live.at](https://mycloud.html5live.at) demo:!demo

### Why and wtf - let me explain:
I started with a humidity/temperature sensor. so I just added these to columns to the db table. After a while I was looking for a more dynamic solution. So I decided to "extend" the api to store the entire json as string and "extract" the data on runtime to "Data List Widget" and "Chart View".
Sorry but the "table List view" is still kind of "static".

Hope I could help and please keep in mind altought SensorLogger should work it is still alpha and experimental!

Any contributions appreciated.

**Comment by CodeUnit** [comment]
Thank you for your answer. 
With the extended api everythink is working perfectly.
You make a gread job with the logger, thank you.
