### ISSUE TITLE
How does this work with nextcloud?

### ISSUE THREAD

**Issue by georg-mayer** [alexstocker/sensorlogger#28]
Hello,

sorry for a newbie question - but I don't find how sensorlogger works with nextcloud. I'm running nextcloud 12 and don't find any menu item which would allow me to configure devices. 

Any help would be appreciated. Maybe it would be good to describe this also in the README.

Thanks and cheers,
Georg

**Comment by alexstocker** [comment]
For [simple](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#simple) sensor logging there is no need to configure a device "manually". Everything is done on the first logging call. Works you DHT22 sensors or any other sensor that provides two data sources (for example temperature and humitidy) 
You can use these php script [for instance](https://github.com/alexstocker/sensorlogger/wiki/Register-devices)

If you want to log data from a device providing more than just temperature and humidity, for example %,ppm,pa,°C you should
1. [register device](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#registerdevice)
2. [get data type ids](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#getdevicedatatypes)
3. [use extend log](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#extended)

Please have a look the [wiki](https://github.com/alexstocker/sensorlogger/wiki)

Any contributions are appreciated
