### ISSUE TITLE
Show data and unregister devices

### ISSUE THREAD

**Issue by user17476566786** [alexstocker/sensorlogger#29]
The registration of devices via "register devices" works fine for me and the devices are shown in the device list.
Nevertheless I can see no data when I perform the extended API call. 
Even when I try to perfom a simple API call I can see no data.

How can I unregister the devices shown in the list?

**Comment by alexstocker** [comment]
Your are almost there!

1) After you registered a device you have to get "dataTypeIds" from the database via api call [getdevicedatatypes](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#getdevicedatatypes) (or you just have a look @ "Data Types" in the menu)

2) To log your data use the [extended](https://github.com/alexstocker/sensorlogger/wiki/API-Calls#extended) createlog api call

3) to view "extended" log data with self defined data types you have two options

- show Chart
- add dashboard widget "Data List" (shows last 10 records)

working demo: [https://mycloud.html5live.at](https://mycloud.html5live.at) demo:!demo

### Why and wtf - let me explain:
I started with a humidity/temperature sensor. so I just added these to columns to the db table. After a while I was looking for a more dynamic solution. So I decided to "extend" the api to store the entire json as string and "extract" the data on runtime to "Data List Widget" and "Chart View".
Sorry but the "table List view" is still kind of "static".

Hope I could help and please keep in mind altought SensorLogger should work it is still alpha and experimental!

Any contributions appreciated.

**Comment by alexstocker** [comment]
At the moment, you can only delete a device from within database by using a DBMS like phpMyAdmin or by using mysql command line interface.

**Comment by user17476566786** [comment]
Here is a litte bit of my code...
I use Qt and Nextcloud to register my devices.
After this I can see my device in the "Devices" list and all data types in the "Data Types" list:

    QString username = "username";
    QString password = "password";
    QNetworkAccessManager manager;
   
    QByteArray data;
    data.append("{ \"_route\":\"sensorlogger.apisensorlogger.registerDevice\", ");
    data.append( " \"deviceId\":\"111111\", ");
    data.append(" \"deviceName\":\"Multi data sensor111111\",");
    data.append(" \"deviceType\": \"RoomMeasurement\",");
    data.append("\"deviceGroup\": \"Room1\",");
    data.append(" \"deviceParentGroup\": \"Appartment\",");
    data.append("\"deviceDataTypes\": [ " );
    data.append(" { ");
    data.append("\"type\": \"temp\",");
    data.append("\"description\": \"Temp\",");
    data.append("\"unit\": \"°C\" ");
    data.append("},");
    data.append("{ ");
    data.append("\"type\": \"hum\",");
    data.append("\"description\": \"Hum\",");
    data.append("\"unit\": \"% r.F.\"");
    data.append(" } ,");
    data.append("{" );
    data.append("\"type\": \"dus\",");
    data.append("\"description\": \"Dus\",");
    data.append(" \"unit\": \"ppm\"");
    data.append("} ,");
    data.append("{" );
    data.append("\"type\": \"vol\",");
    data.append("\"description\": \"Vol\",");
    data.append(" \"unit\": \"dB\"");
    data.append("}");
    data.append("]");
    data.append("}");

    QNetworkRequest request(QUrl("http://MYNEXTCLOUD/nextcloud/index.php/apps/sensorlogger/api/v1/registerdevice/"));
    request.setHeader(QNetworkRequest::ContentTypeHeader, QString("application/json"));
    QByteArray concatenated;
    concatenated.append( username + ":" +  password);
    QByteArray basicAuth = concatenated.toBase64();
    QByteArray headerData = "Basic " + basicAuth;
    request.setRawHeader("Authorization",headerData);
    QNetworkReply* reply = manager.post(request,data);

    QEventLoop loop;
    connect(reply, SIGNAL(finished()), &loop, SLOT(quit()));
    loop.exec();
`

Then I perfom the extended API call every two seconds using the data type IPs from the "Data Types" list:

    QString date = QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm:ss");
    QString username = "username";
    QString password = "password";
    QNetworkAccessManager manager;

    QByteArray data;
    data.append("{");
    data.append("\"date\":" + date);
    data.append("\"deviceId\":\"111111\",");
    data.append("\"data\" : [");
    data.append("{");
    data.append("\"dataTypeId\": 26,");
    data.append("\"value\": 38");
    data.append("},");
    data.append("{");
    data.append("\"dataTypeId\": 27,");
    data.append("\"value\": 37.012");
    data.append("},");
    data.append("{");
    data.append("\"dataTypeId\": 28,");
    data.append("\"value\": 9.225");
    data.append("},");
    data.append("{");
    data.append("\"dataTypeId\": 29,");
    data.append("\"value\": 3124");
    data.append("}");
    data.append("]");
    data.append("}");

    QNetworkRequest request(QUrl("http://MYNEXTCLOUD/nextcloud/index.php/apps/sensorlogger/api/v1/createlog/"));
    request.setHeader(QNetworkRequest::ContentTypeHeader, QString("application/json"));
    QByteArray concatenated;
    concatenated.append( username + ":" +  password);

    QByteArray basicAuth = concatenated.toBase64();
    QByteArray headerData = "Basic " + basicAuth;
    request.setRawHeader("Authorization",headerData);
    QNetworkReply* reply = manager.post(request,data);

    QEventLoop loop;
    connect(reply, SIGNAL(finished()), &loop, SLOT(quit()));
    loop.exec();
`
But I still can't see any data when I click on the "Chart" Button or when I create a new dashboard widget...

**Comment by alexstocker** [comment]
checkout [curl examples](https://github.com/alexstocker/sensorlogger/tree/master/tests/curl)
I've fixed some bug in version 0.0.4.1 but I don't think that this fix should affect your nextcloud install
