### ISSUE TITLE
Add postgres support

### ISSUE THREAD

**Issue by mopshizz** [alexstocker/sensorlogger#32]
I really would like to try the sensorlogger but my NC is running on postgres. Is support for postgres planned for the future?

**Comment by alexstocker** [comment]
Thanx for your question. Adding postgres support sounds good to me but unfortunately there is so much to fix and enhancements to add but so less time. Sorry. Please check back later. Any contributions are warmly welcome.

**Comment by LordVan** [comment]
Hi.
I just found this and thought I might want to use it for my newly (yesterday) finished RaspberryPI based temperature logger ;)

I haven'T had the time to look at the code yet, but do you use any mysql specific SQL? - i might be able to help out at least, just would like to know what to expect approx.

**Comment by alexstocker** [comment]
Thanx for your offer :-) 

These protected methods may be reworked first

[ApiSensorLoggerController::insertExtendedLog](https://github.com/alexstocker/sensorlogger/blob/d304f86d5c629e6b3d91c0991558333e059bd935/controller/apisensorloggercontroller.php#L91)
[ApiSensorLoggerController::insertLog](https://github.com/alexstocker/sensorlogger/blob/d304f86d5c629e6b3d91c0991558333e059bd935/controller/apisensorloggercontroller.php#L112)
ApiSensorLoggerController::insertDeviceType
ApiSensorLoggerController::insertDeviceGroup
ApiSensorLoggerController::insertDataTypes
ApiSensorLoggerController::insertDeviceDataTypes
ApiSensorLoggerController::insertDevice

[/appinfo/database.xml](https://github.com/alexstocker/sensorlogger/blob/master/appinfo/database.xml)
[/appinfo/info.xml](https://github.com/alexstocker/sensorlogger/blob/master/appinfo/info.xml)

have to be updated too I think

Time effort (best guess): a view hours or a night shift :-)

**Comment by kenda** [comment]
What does closing the issue mean here? I really would like to use this app but this issue is blocking.

On a first quick view, there doesn't seem to be non-standard queries, or am I missing something?
