### ISSUE TITLE
Use server time when json does not contains the date field

### ISSUE THREAD

**Issue by bargru** [alexstocker/sensorlogger#33]
On some systems, it may be cumbersome to create the correct timestamp for the json that is sent to the server.

For example under esp2866 with the arduino ide. There I have to fetch the time from an NTP server. Then, convert the time to the correct time zone and paying attention to daylight saving time. And then the time stamp has to be formatted. To do this I need several librarys and lines of code.

It would be easier if the server time is stored automatically if the json does not contain the date field. Or in the json it can be specified explicitly that the server time should be used (ex.: `["date"] = "server-time"`).

By the way: I like this application very much, even if it is not finished yet.

**Comment by alexstocker** [comment]
Thanx for your suggestion. Hopefully I find some spare time on my holidays to do some work on sensorlogger again.

**Comment by e-alfred** [comment]
@bargru I am interested in using Arduino or ESP2832/ESP32 boards with Sensorlogger. Could you share a bit of how you do send data to Sensorlogger with them? Any help is greatly appreciated.

**Comment by alexstocker** [comment]
@e-alfred  Have a look at https://github.com/alexstocker/sensordata/blob/master/sensordata.ino
Hope it helps.

**Comment by e-alfred** [comment]
@alexstocker Thanks, I will take a look into it!

**Comment by alexstocker** [comment]
Added server time to log if date is not set
