### ISSUE TITLE
Add ability to rename device in Sensorlogger

### ISSUE THREAD

**Issue by e-alfred** [alexstocker/sensorlogger#34]
Hello,

I created two devices which have the name "Default device". Is it possible to rename them into something more descriptive? If not from the UI, is it possible to change the name in the database?

**Comment by alexstocker** [comment]
Klick the device at "list" view. Sidebar (right) should appear. There you can xhange device name.

Kinder
Alex

7. November 2017 19:31, "e-alfred" <notifications@github.com (mailto:%22e-alfred%22%20<notifications@github.com>)> schrieb:
	Hello, 

	I created two devices which have the name "Default device". Is it possible to rename them into something more descriptive? If not from the UI, is it possible to change the name in the database?

**Comment by alexstocker** [comment]
[see screenshot](https://camo.githubusercontent.com/862066d216d133ba9218bd627f1cfc501d9e7a17/687474703a2f2f7777772e68746d6c356c6976652e61742f77702d636f6e74656e742f75706c6f6164732f323031372f30332f73656e736f726c6f676765725f64657669636544657461696c735f656469742e706e67)
