### ISSUE TITLE
Empty Chart with Simplelog

### ISSUE THREAD

**Issue by silence87** [alexstocker/sensorlogger#36]
Hi all, 

without provided data array value, the chart data remain empty. 
In the Table oc_sensorlogger_logs, columns temperature and humidity are filled.
In column data there is a JSON array with "_route:" value starting. 
for example: {"_route":"sensorlogger.apisensorlogger.createLog","deviceId":"28-000006a2e6ae","temperature":21.81,"humidity":0,"date":"2017-11-20 20:03:40"}

With multivalue posts, there are no issues.

Did i something wrong? 

NC 12.0.3
Apache 2.4.27, PHP 7.0.21, MariaDB 10.0.31 on Synology DSM 6

**Comment by alexstocker** [comment]
Hmmm?!
Under investigation. Please be patient.

**Comment by alexstocker** [comment]
@silence87 After a while of investigation I gave up. Sorry. I was not abel to reproduce your problem. 
Would you please upgrade to version [0.0.5nc](https://github.com/alexstocker/sensorlogger/releases/tag/0.0.5nc) and let me know if the problem still persists. Thanx.

**Comment by silence87** [comment]
ok thank you, i will test this.
just uninstall the old version and move the zip into the apps dir?

**Comment by alexstocker** [comment]
If you did not obtain SensorLogger from the app store 

1. download the latest release for nextcloud. This would be [v0.0.5nc](https://github.com/alexstocker/sensorlogger/releases/tag/0.0.5nc) at the moment
1. Extract/unzip content to apps/sensorlogger

Please let me know if installing v0.0.5nc fix the problem. Thanx.
