### ISSUE TITLE
implement ability to delete measurements from the list

### ISSUE THREAD

**Issue by driverinla** [alexstocker/sensorlogger#37]
It would be great if there was a way to delete measurements from the list. Sometimes I do some test measurements to see if things are working and I have no way to remove them. They affect the graphs and other listings. 

I am not sure if this is easy to implement, but I believe it will improve the testing of different sensors greatly.

Thanks!

**Comment by alexstocker** [comment]
@driverinla added deleteLog to List view. checkout devel branch.

**Comment by alexstocker** [comment]
@andreapx 
- delete (single) measurement ![delete sensorlogger measurement](https://www.html5live.at/wp-content/uploads/2018/05/sensorlogger_list_001.png)
- delete device (if no measurments exist) ![delete sensorlogger device](https://www.html5live.at/wp-content/uploads/2018/05/sensorlogger_devices.png)

implemented already
- remove/whipe/truncate device including measurements planned #49

**Comment by alexstocker** [comment]
@andreapx 
If your are using version 0.0.5 for owncloud installed from marketplace or master repository please be patient.
development will be merged to master soon. Releasing sensorlogger 0.0.6 for owncloud as soon as possible. If you can not wait, checkout devel branch.

**Comment by andreapx** [comment]
@alexstocker 
I'm using the beta release for NextCloud 13.
I'll wait.
Thanks!!!
