### ISSUE TITLE
Initial example script not working

### ISSUE THREAD

**Issue by OzzieIsaacs** [alexstocker/sensorlogger#41]
## Expected Behavior
after excecuting the example script from https://github.com/alexstocker/sensorlogger/blob/master/tests/curl/post.php a new device should appear on the UI.

## Actual Behavior
Nothin happens. 
Script returns false
No log entry.
(Got sensorloger running with registering a device and generating the nesessary datatypes with the other example scripts)

## Steps to Reproduce the Problem

  1. Fresh installation of sensorlogger on nextcloud 12 (empty databaseentries for sensorlogger)
  2. Generate app password and fill data to example script
  3. Excecute https://github.com/alexstocker/sensorlogger/blob/master/tests/curl/post.php

## Specifications

  - Version: Nextcloud 12.04
  - Platform: Ubunutu 16.04 LTS
  - Subsystem: php 7

**Comment by alexstocker** [comment]
Hi @OzzieIsaacs !
Did you install SensorLogger from Marketplace or GitHub Repository?

**Comment by OzzieIsaacs** [comment]
First installed from marketplace, after this didn‘t work (this issue) I replaced it with the github version (first the wrong one for owncloud), afterwards replaced it with the version from the Nextcloud app website. Before each replace I deleted the sensorlogger folder in the apps directory

**Comment by alexstocker** [comment]
Sorry @OzzieIsaacs 

Could not reproduce this issue.

1. Did a fresh nextcloud install (12.0.5)
2. activated SensorLogger from the Apps (Market)
3. added a new App Password (aka Pin)
4. replaced $username and $token in test/curl/post.php
5. executed php test/curl/post.php

et voila - a new device (deviceId: 666666-fe8c-11e6-bc64-92361f002671) appears in the user interface a expected.

But thanx anyway. Any contribution/report is warmly welcome.
