### ISSUE TITLE
Nextcloud 13 support

### ISSUE THREAD

**Issue by e-alfred** [alexstocker/sensorlogger#42]
Hello,

Nextcloud 13 will be released soon. Can you provide a new version to the app store that supports the new release as well?

**Comment by alexstocker** [comment]
Updated max supported nextcloud version and released sensorLogger [0.0.5-nc.13](https://github.com/alexstocker/sensorlogger/releases/tag/0.0.5-nc.13).

Please notice that the next "stable" release will be version 0.0.6nc
