### ISSUE TITLE
sensorlogger at webspace

### ISSUE THREAD

**Issue by ratzebichl** [alexstocker/sensorlogger#44]
Hi Alex,
does sensorlogger works on webspace also?
I uploaded the file sensorlogger-0.0.5-nc.13 in the apps directory.
it is not possible for me to execute   php post.php  on command line.
Is there another way?

**Comment by alexstocker** [comment]
Hi ratzebichl

Sure. You can use SensorLogger with any supported ownCloud or nextCloud instance. 

Which sensor data do you want to log?
