### ISSUE TITLE
Assistance with setup to our temp monitor using json file

### ISSUE THREAD

**Issue by greavette** [alexstocker/sensorlogger#47]
We use an avtech temp monitor in  our office. I can retrieve through the website to our temp monitor a Json file:  https://avtech.com/articles/4639/find-room-alert-monitor-json-data/

To display the data from our avtech temp monitor.

Can sensor logger read this json file as an input?

Thank you in advance for any assistance you can provide.

**Comment by alexstocker** [comment]
Hi @greavette 

Sorry. That's not the way SensorLogger is working at the moment.

Currently SensorLogger does not "ask" a sensor for data. SensorLogger is waiting that an appliance "pushes" data.
I'm pretty sure, the hardware vendor you are talking about, does not provide a legal way to "extend" it ;-) So, if you want to store data somewhere else you need a solution that works the other way around.

Therefor SensorLogger, or any other app, would need a possibility to "configure" a device 
1. with an given url where data can be "pulled" from
2. and a kind of (JSON) data mapping 

Hope I could help a little

kindest
Alex
