### ISSUE TITLE
make the app available for Nextcloud 13

### ISSUE THREAD

**Issue by daniu-de** [alexstocker/sensorlogger#48]
Hi,

I really like this app and would highly appreciate further development.
Actually I use it with Nextcloud 13 which is unfortunately officially not supported but seems to work as good as Nextcloud 12. I think it just needs to be changed ...

**Comment by alexstocker** [comment]
Thanx @daniu-de 

Release follows asap

**Comment by alexstocker** [comment]
@daniu-de 

[SensorLogger for Nextcloud 13 out now](https://www.html5live.at/2018/05/sensorlogger-for-nextcloud-13-out-now/)

Current SensorLogger for Nextcloud version: [0.0.6nc](https://github.com/alexstocker/sensorlogger/releases/tag/0.0.6nc)

Have fun!
