### ISSUE TITLE
widgets on dashboard are not persistant

### ISSUE THREAD

**Issue by daniu-de** [alexstocker/sensorlogger#51]
## Expected Behavior
I setup widgets on the dashboard - 2 sensors - charts on top, list on the bottom - looks nice, after reloading the page the view is cluttered

## Actual Behavior
widgets are cluttered and do not stay in the same order after reload
first row shows: data list of second sensor - chart second sensor - data list first sensor
second row shows: chart of second sensor

## Steps to Reproduce the Problem

  1. setup 2 charts for 2 sensors, arrange them in the top row the charts, below a row with the data lists
  2. reload page

## Specifications

  - Version: 0.0.6
  - Browser: Firefox 52.5.0

**Comment by alexstocker** [comment]
@daniu-de 

Thanx for reporting.

You are right. Widgets do not have sorting. May be in future releases. And yes there is a lot of styling work to do left. But remember SensorLogger is still **alpha**.

Anyway. I'll do my best. Any contributions welcome.

kin

**Comment by alexstocker** [comment]
feature Branch: [51-orderable-dashboard-widgets](https://github.com/alexstocker/sensorlogger/tree/51-orderable-dashboard-widgets)

Features:
* Sort/order Widgets
* resize Widgets
* save state on change 
![Auswahl_006](https://user-images.githubusercontent.com/6260467/58057179-4371fa80-7b64-11e9-8878-4f123b3c1055.png)
