### ISSUE TITLE
NC 14 compatibility

### ISSUE THREAD

**Issue by Olen** [alexstocker/sensorlogger#53]
## Expected Behavior
The app should be compatible with NextCloud 14

## Actual Behavior
The app might not be compatible with NextCloud 14 (not tested)

## Steps to Reproduce the Problem

  1. Install NC 14
  2. Try to install app

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by alexstocker** [comment]
@Olen 

Thanx for your request. [SensorLogger for Nextcloud 14](https://www.html5live.at/2018/09/sensorlogger-for-nextcloud-14-out-now/) is now available at apps.nextlcoud.com. 
Please check it out and let me know if any error occur.

kindest
Alex
