### ISSUE TITLE
Fresh Reinstall

### ISSUE THREAD

**Issue by ernesst** [alexstocker/sensorlogger#55]
**Is your feature request related to a problem? Please describe.**
I would like to know which tables to wipe to cleanup the app and perform a fresh reinstall ?

Thanks
Kevin

**Comment by alexstocker** [comment]
Hi @ernesst 

If you wish to **delete SensorLogger completely** from your owncloud or nextcloud instance, **deactivate and uninstall** SensorLogger, **logon** to your **DMBS** (phpMyadmin for instance) and

**DELETE** SensorLogger database **tables** (should not be necessary, done by uninstall)

- [PREFIX]sensorlogger_data_types
- [PREFIX]sensorlogger_devices
- [PREFIX]sensorlogger_device_data_types
- [PREFIX]sensorlogger_device_groups
- [PREFIX]sensorlogger_device_types
- [PREFIX]sensorlogger_logs

**DELETE** SensorLogger **widget configurations** from
- [PREFIX]preferences **where appid = sensorlogger**

kindest
Alex

**Comment by ernesst** [comment]
Thanks work great, my reinstall is cleaner now.
