### ISSUE TITLE
Pulling data via NC Cron?

### ISSUE THREAD

**Issue by Rello** [alexstocker/sensorlogger#56]
Hello,

congratulations to your app. nice effort.

I would like to know if you thought about a way to let the app (cron on NC) pull information - compared to the current push of the sensor itself.

one possible case: track your download statistics in git. currently i am checking on a daily basis the statistics
(e.g. https://api.github.com/repos/rello/audioplayer/releases) and read the `"download_count": xxxx,`
Afterwards I store it in an excel and create a pivot-chart

As this is perfectly structured information it might be interesting in some place in sensorlogger to define

- the url (e.g. `https://api.github.com/repos/rello/audioplayer/releases`)
- the array for the information (e.g. `['assets']['download_count']`)

This information is then read regularly and added into the sensorlogger db (as cumulative value).
I would love to have an automated way to track the download stats which might in this case (think of a pull-template) be interesting for many app devs

anything ever thought about?

**Comment by alexstocker** [comment]
@Rello 

Thanx for your interesting idea. 
Background Jobs/CronJobs are scheduled for release 0.2.0. But there is still a long way to go.

Any way. We could start talking about possible requirement. What do you think?

kindest
Alex

**Comment by Rello** [comment]
I think there are several steps to implement

- general cron framework
- 1st: UI to register cron-tasks
- 2nd: UI to assign different time schedules to cron-tasks (hourly/daily/weekly)
- UI to create custom cron-tasks as mentioned above and find a way to parse array values

...quite some job to do :-)
