### ISSUE TITLE
Options to delete all log entries or per device

### ISSUE THREAD

**Issue by dr0jf** [alexstocker/sensorlogger#57]
Hi! I just tested my first sensor and got everything working. Sensor Logger seems to be exactly what I need, thanks for your work!

When I wanted to get rid of a few hundred log entries I had from testing, I could neither find a way to delete all log entries for a certain device, nor an option to delete all entries.

I think there could be two options that people might like to have
- deviceList: delete all logs per device (maybe next to the button to delete the device itself)
- showList:  delete all log entries

**Comment by dr0jf** [comment]
I found the option to delete the device and logs (#49). I also found #37 but don't see options in the GUI. Maybe I'm missing something. I am using 0.0.8 on Nextcloud.

**Comment by alexstocker** [comment]
Have a look at device details (klick on a device in deviceList will open sidebar). At the bottom you'll find the **wipeOut** trashbin button.

**Attention** wipeout will delete your device, depending dataTypes and ALL logs depending to this device

![image](https://user-images.githubusercontent.com/6260467/46160214-6fadd380-c282-11e8-8207-026fb59791e8.png)
