### ISSUE TITLE
Simple Android Sensor Logger

### ISSUE THREAD

**Issue by mr-gosh** [alexstocker/sensorlogger#59]
There are many unused Android phones out there and it would be awesome if there is a simple way to use these devices to log sonsors to the sensor logger webui.

I only found apps that log into .csv - but nothing that is able to deliver api calls.

So this feature request consists of two questions:

1. is there an app that is able to log android sensors to sensorlogger?
2. is there a way to monitor a synced .csv file for changes and import these into the webui?

**Comment by alexstocker** [comment]
@mr-gosh 

ad. 1)
I started to build an app that should do the job. To be honest: at the moment, it doesn't ;-) But if you want to take a challenge, check this out https://github.com/alexstocker/sensorlogger-android. Any contribution warmly welcome.

ad 2)
in short: no.
