### ISSUE TITLE
sensorlogger stops working 

### ISSUE THREAD

**Issue by vitoller** [alexstocker/sensorlogger#69]
## Expected Behavior
ignore non numeric dataTypeId's

## Actual Behavior
sensorlogger failure 
I had to delete all entries in the "oc_sensorlogger_logs" database table

## Steps to Reproduce the Problem

  1. when using the extended protocoll send character as dataTypeId
  2. reload sensorlogger page in nextcloud

## Specifications

  - Version: 0.0.9nc
  - Platform: linux
  - Subsystem: nextcloud

**Comment by alexstocker** [comment]
@vitoller 
Doing more data validation would be fine, but will cause much more server load too. I think providing an validation API call would be much better.

**Comment by alexstocker** [comment]
@vitoller 
Added some more validation stuff. planned for version 0.1.0nc

**Comment by vitoller** [comment]
that was quick - thanks
