### ISSUE TITLE
Erklärung erforderlich

### ISSUE THREAD

**Issue by alexstocker** [alexstocker/sensorlogger#70]
https://github.com/alexstocker/sensorlogger/blob/a4e341689b3dfaf4bb0c021add7fe1c9509e0834/controller/apisensorloggercontroller.php#L104
https://github.com/alexstocker/sensorlogger/blob/a4e341689b3dfaf4bb0c021add7fe1c9509e0834/controller/apisensorloggercontroller.php#L133

Erkläre mir mal warum du diese Änderung machen würdest

https://github.com/alexstocker/sensorlogger/blob/a4e341689b3dfaf4bb0c021add7fe1c9509e0834/controller/apisensorloggercontroller.php#L196

Weshalb sollte hier nochmals is_numeric besser geeignet sein als is_int?

Bevor du antwortest überlege genau, lies unbedingt auf php.net in den Funktionsreferenzen nach und kontrolliere welchen Typ die Variablen haben sollen bzw. müssten.

**Comment by alexstocker** [comment]
Welche IDE verwendest du? Aus persönlicher Erfahrung kann ich sagen, auch wenn ich mit vi, mc und anderen Editoren zu arbeiten gelernt habe, hätte ich viel früher mal PHPStorm eine Chance geben sollen. Eclipse und Netbeans sind zwar auch ok aber ehrlich, da liegen mittlerweile Welten dazuwischen.

**Comment by alexstocker** [comment]
https://github.com/alexstocker/sensorlogger/blob/a4e341689b3dfaf4bb0c021add7fe1c9509e0834/controller/apisensorloggercontroller.php#L368

Diese Methode ist dafür gedacht zu prüfen ob ein Sensor bereits registriert wurde und true oder false zurück zugeben. return -1 ist eher schräg. Sorry

**Comment by issb-gh** [comment]
zu 3. Stimmt, check-Funktionen sollten true oder false liefern, das sehe ich genau so. Das wird geändert.
zu 2. Die IDE muss ich noch suchen. Ich habe erst mal notwpad+ verwendet. Dachte das reicht hierfür, aber ist etwas ungemütlich.
zu 1. Ok, ich habe noch nicht zu ende überlegt und kann jetzt nur sagen, was der Grund war, aber noch nicht, ob es 100%ig richtig ist.
Da ich die Klassen in den Quellen DataType und Device nicht genutzt habe, somit auch die members id der Klassen nicht, war ich auf die Ergebnisse der SQL-Abfragen angewiesen. Diese liefern für ID einen größeren Type als int, denn das Feld id ist in der DB BIGINT.
Die Funktion is_int für das Feld id lieferte also false o. 0 zurück.

Ich sehe nun mal nach den Klassen Device und DataType nach der Benutzung von FromRow. Vielleicht ist dann is_int die bessere Wahl.

**Comment by issb-gh** [comment]
Ok Info auf http://php.net/manual/de/language.types.integer.php.
Laut Doku ist der Type also vom Betriebssystem abhängig.
Bei Integer Type int handelt sich auf Deiner Plattformen offensichtlich um 64 Bit-Typen. Ich hingegen und evtl. auch andere User bennutze als Webserver ein 32-Bit System, denn die Hardware ist ein ARM Prozessor (CubieBoard - Cubietruck mit Ubuntu 16.04 LTS - Architektur: armv71).
Das ist der Grund, warum is_int bei mir false lieferte und auf anderen Systemen true.
Ist es dann nicht schon aus diesem Grund besser, is_numeric zu verwenden, denn bei einer SQL-Abfrage nach einer Id ist es wichtig zu wissen, ob eine Zahl geliefert wurde, nicht ob der Typ der Zahl int ist?

**Comment by issb-gh** [comment]
var_dump(PHP_INT_MAX): int(2147483647) 
var_dump(PHP_INT_SIZE): int(4)

**Comment by issb-gh** [comment]
$deviceGroupId = (int)$this->insertDeviceGroup($params['deviceGroup']);
hier würde is_int sicher true zurückliefern, wenn ein Datensatz gefunden wurde und eine GroupID in deviceGroupId enthalten ist.
Auf 32-Bit Systemen  könnte aber rein theoretisch ein Datenüberlauf stattfinden, wenn die ID größer 2147483647 ist. In diesem Fall würde sich der Widerspruch der beiden Typen (DB-Fields ID: BIGINT und  PHP-Type: int) deutlich zeigen.
is_numeric wäre meiner Meinung nach die bessere Wahl, denn wir wollen wissen, ob die DB-Abfrage ein Ergebnis, speziell eine ID geliefert hat. Die muss eine Zahl beliebiger Länge sein und nicht unbedingt int sein.

**Comment by alexstocker** [comment]
Also nochmals von Anfang an
### checkRegisteredDevice
```
	protected function checkRegisteredDevice($params) {
	    if(isset($params['deviceId'])) {
            $device = SensorDevices::getDeviceByUuid(
                $this->userSession->getUser()->getUID(),
                $params['deviceId'],$this->db
            );

			if($device) {
				return true;
			}
		}
		return false;
	}
```
Soll und darf nur _bool_ true/false zurück geben. Wenn **checkRegisteredDevice** _false_ zurück gibt und du aber _true_ erwartest dann liegt das daran das kein Device gefunden wurde. Warum das so ist hat aber nichts mit der plattformabhängigen _PHP_INT_MAX_ zutun. Da liegt das Problem wo anders.
### insertDeviceGroup
```
	protected function insertDeviceGroup($string) {
		$sql = 'INSERT INTO `*PREFIX*sensorlogger_device_groups` (`user_id`,`device_group_name`) VALUES(?,?)';
		$stmt = $this->db->prepare($sql);
		$stmt->bindParam(1, $this->userSession->getUser()->getUID());
		$stmt->bindParam(2, $string);
		if($stmt->execute()){
			return (int)$this->db->lastInsertId();
		}
		return false;
	}
```
Muss die _Id_ als _Integer_ zurück liefern (zur sicherheit zu int gecasted) wenn der INSERT erfolgreich war. Wenn nicht muss **insertDeviceGroup** _false_ zurück gegeben werden. Das der Integer größer ist als 2^31 ist aus meiner Sicht äußerst unwahrscheinlich, es sei denn du hast schon mehr als 2.147.483.647 Device Groups angelegt ;-) Falls das nicht der Fall ist und du dennoch nicht wie erwartet einen Integer erhältst sonder _false_ oder ein _float_, dann gibts ein Problem mit BIGINT(20). Ich kann mir das zwar nicht vorstellen, will es aber auch nicht ausschließen.

_is_int_ durch _is_numeric_ zu ersetzen würde hier nur ein _Symptom bekämpfen_ aber nicht die Ursache des Problems beseitigen.

### Conclusio
Wenn BIGINT(20) auf 32-Platformen nicht das Problem sehe ich die Notwendigkeit nicht _is_int_ durch _is_numeric_ zu ersetzen.

### Hinweise
* use xdebug
* sieh dir die system und error logs an (syslog, mysql, dmesg, php, apache|nginx, mysql) die owncloud.log wird nicht ausreichen und ist auch imho etwas schwer zu lesen.

**Comment by issb-gh** [comment]
Der Mengenbereich von 2^32-1 wird bestimmt nicht in erster Linie von den DeviceGroups, aber evtl. von den Logs erreicht werden.
Die DB wurde so designed, dass für das Feld id ein 8 Byte großer Datentype definiert wurde. In den SensorLogger-Quellen wird jedoch auf den PHP-Type int vertraut, der ist unter 64-Betriebssysteen ebenfalls 8 Byte groß, aber unter 32-Bit-Systemen eben nur 4 Byte.
Das wäre der erste Widerspruch.
Wir müssen auch daran denken, dass nicht ein User alleine sehr viele Devices usw. anlegen wird, sondern alle User zusammen. Wenn meine 20 Sensoren jede Stunde schon 7200 Einträge erzeugen, weil ich die Zeit mit 10 Sekunden Abstand ziemlich kurz gewählt habe, dann haben wir am Tag 172800 Einträge. Im Jahr ca. 63.072.000. Gibt es noch mehr solche testwütigen Owncloud-User, dann kann 2^32 schon erreicht werden.

**Comment by alexstocker** [comment]
Dann hast aber auf einem 32-bit System sowieso ein Problem ;-)

**Comment by issb-gh** [comment]
Hah, :-) Könnte, muss aber nicht. Das will ich eben mal sehen, wie dieses Problem aussieht. Denn in der MySQL-DB ist der Feldtyp ebenfalls BIGINT, also 64 bit. Ich benutze auch einen 32-Bit-MySQL-Server (auf einer expliziten Maschine - BananaPiPro).
Auf 32-Bit-Systemen gibt es beispielsweise in VisualC++ den Datentyp int64. Gibt es einen 64-Bit Integer-Datentype bei PHP für 32-Bit-Systeme?

**Comment by alexstocker** [comment]
Das  hängt von der platformspezifischen Größe des Wertes PHP_MAX_INT ab der bestimmt wie Groß Integer werden darf. Um zu testen wie sich ein 32bit System bei überlauf verhält ...

```mysql
ALTER TABLE `table` AUTO_INCREMENT = 2147483647  ;
```

**Comment by alexstocker** [comment]
@issb-gh falls noch weiteres zu klären ist einfach wieder aufmachen oder neues Issue anlegen. Danke für deinen Einsatz.
