### ISSUE TITLE
Eindeutigkeit der Device ID (UUID oder String) benutzerabhängig oder nicht

### ISSUE THREAD

**Issue by issb-gh** [alexstocker/sensorlogger#71]
Der Benutzer von SensorLogger rechnet damit, dass er über die Menge der Kombinationen u. Permutationen einer UUID verfügt (Gemeint ist die Menge aller UUIDs einer bestimmten Länge). Dem ist aber nicht so, denn alle Benutzer teilen sich die Menge. 
Zum Beispiel gehört die UUID xyz dem Benutzer A, die UUID 123 gehört dem Benutzer B. Der Benutzer B kann kein Gerät mit der UUID xyz anlegen, denn das wurde bereits von Benutzer A durchgeführt.
Ich sehe keinen Vorteil der Eindeutigkeit innerhalb der Tabelle SensorDevices. Viel sinnvoller ist die Eindeutigkeit innerhalb des Benutzerkontextes.
Zum Beispiel soll Benutzer A ein Gerät xyz genau einmal anlegen können und auch der Benutzer B.

Was spricht dagegen?

**Comment by alexstocker** [comment]
Ja ich versteh schon. Ich bin da selbst einem Irrtum aufgesetzten. Ursprünglich hab ich angenommen dass ich das eh schon so gemacht hab.

Planned for Release 0.1.0

**Comment by alexstocker** [comment]
Du kannst branch 0.1-devel auschecken und mal testen.
```
git pull
git checkout 0.1-devel
```

**Comment by alexstocker** [comment]
Evtl. noch ein wichtiger Hinweis. Das Database Scheme wird mittels Migrations aktualisiert.
https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/database.html#database-migrations
Ob das bei Nextcloud auf noch so funktioniert oder geändert wurde weis ich noch nicht.

**Comment by alexstocker** [comment]
UUID (device identifier) now unique for each users. Migrations added. Replaces database.xml vom Release 0.1.0 onwards! 
**sensorlogger_devices.uuid**  and
**sensorlogger_logs.device_uuid** 
should be **renamed** to identifier device_identifier respectifely **one day**
