### ISSUE TITLE
Please Close

### ISSUE THREAD

**Issue by AnderCrafter** [alexstocker/sensorlogger#72]
Please Close

**Comment by alexstocker** [comment]
Hi @AnderCrafter 

Hast du dir deine Fragen selbst beantworten können? Sieht zumindest so aus ;-)

Ein Hinweis noch zu Arduino/NodeMCU:
Hier findest du ein einfaches Beispiel
https://github.com/alexstocker/sensordata/blob/master/sensordata.ino

Freut mich das du dich für SensorLogger interessierst. Any contribution welcome!

kindest
Alex
