### ISSUE TITLE
Interner Serverfehler beim Öffnen

### ISSUE THREAD

**Issue by AnderCrafter** [alexstocker/sensorlogger#75]
![screenshot 2019-02-23 at 14 20 18](https://user-images.githubusercontent.com/39222199/53286992-4d0ee080-3776-11e9-948f-03f73449f630.png)

Hi, habe die neuste Sensorlogger version installiert.

Meine Systemdetails:

> Ubuntu 18.04.1
> PHP 7.2
> Apache 2

Logs:
https://pastebin.com/f8Kr3Fs6
Startend von der Request Id die ich erhielt endent mit ende des logs

**Comment by alexstocker** [comment]
@AnderCrafter 
Danke für den Report. Irgend etwas stimmt mit dem table prefix nicht 

```php
Base table or view not found: 1146 Table 'nextcloud.oc_sensorlogger_devices' doesn't exist","Code":0,"Trace":
```
Kannst du mal nachsehen ob diese Table existiert bzw. wie's richtig benannt ist?

**Comment by AnderCrafter** [comment]
Der Fehler könnte auch auf meiner Seite sein, kannst du mir einen sqldump/.sql der Tabellen von sensorlogger schicken ?

**Comment by alexstocker** [comment]
@AnderCrafter 

Ich denke eher ich hab die Umstellung von database.xml auf DB Migrations nicht gut genug getestet. 

So sollte das Schema aussehen
[sensorlogger_create_dump.sql.zip](https://github.com/alexstocker/sensorlogger/files/2912061/sensorlogger_create_dump.sql.zip)
```sql
CREATE TABLE `oc_sensorlogger_data_types` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `description` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `type` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `short` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `oc_sensorlogger_device_data_types` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `device_id` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `data_type_id` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `oc_sensorlogger_device_groups` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `device_group_name` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `oc_sensorlogger_devices` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `uuid` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `type_id` bigint(20) NOT NULL DEFAULT '0',
  `group_id` bigint(20) NOT NULL DEFAULT '0',
  `group_parent_id` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `sensorlogger_devices_unique_idx` (`user_id`,`uuid`),
  KEY `type_id_idx` (`type_id`),
  KEY `group_id_idx` (`group_id`),
  KEY `group_parent_id_idx` (`group_parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `oc_sensorlogger_device_types` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `device_type_name` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `oc_sensorlogger_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `device_uuid` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `temperature` double DEFAULT NULL,
  `humidity` double DEFAULT NULL,
  `data` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
```

**Comment by alexstocker** [comment]
@AnderCrafter 
Hmmm... konnte das Problem leider noch nicht reproduzieren

- OS Ubuntu 18.04
- PHP 7.2.14
- Apache 2.4.29
- MySQL 5.7.25
- Tested with Nextcloud Versions : 15.0.0 & 15.0.5 RC2

Das wird denke ich weitest gehend deckungsgleich mit deinem Environment sein
Läuft PHP bei als Apache Module (mod_php) oder möglicherwise via PHP-FPM?

**Comment by AnderCrafter** [comment]
Ok, also mit importiertem SQL DUMP läuft es bei mir wieder

**Comment by AnderCrafter** [comment]
> @AnderCrafter
> Hmmm... konnte das Problem leider noch nicht reproduzieren
> 
> * OS Ubuntu 18.04
> * PHP 7.2.14
> * Apache 2.4.29
> * MySQL 5.7.25
> * Tested with Nextcloud Versions : 15.0.0 & 15.0.5 RC2
> 
> Das wird denke ich weitest gehend deckungsgleich mit deinem Environment sein
> Läuft PHP bei als Apache Module (mod_php) oder möglicherwise via PHP-FPM?

Ja, ich nutze php-fpm

**Comment by alexstocker** [comment]
Von welcher SensorLogger Version hast du das update gemacht
0.0.9 > 0.1.0 ?

**Comment by AnderCrafter** [comment]
Vermutlich, weiß ich aber nicht genau

**Comment by alexstocker** [comment]
Sorry. Hab' nochmal auch mit PHP-FPM getestet (fresh install and upgrade from 0.0.9) aber das problem dürfte doch woanders gelegen haben. Nach dem's mit dem dump funktioniert schließe ich dieses Issue. 
Falls dir noch was einfallen sollte, lass es mich bitte wissen.

Danke nochmals für deinen Report.
