### ISSUE TITLE
HTTP ERROR 500 after just installing sensorlogger

### ISSUE THREAD

**Issue by ibaranov-cp** [alexstocker/sensorlogger#76]
**Platform you are using**
> owncloud 

**Sensors/Hardware**
> Information about the hardware you want to log data from
Likely small microprocessors, but haven't gotten there yet

**Your Goals**
> Tell us what goals you pursue
I'd like to log data

**Your Question**
> Please keep your question as short and clear as possible. Thanx
Hello,
I've been running owncloud for a while, just recently upgraded to 10.1.0.4
I then decided to try sensorlogger, however, after install from marketplace, when I click the sensorlogger button, I get back a 500 error. The owncloud site itself is up.
(Here: https://mrrobot.ca/owncloud/apps/sensorlogger/ )

I can't seem to find any info on debugging, what are next steps?
Best wishes,
Ilia B.

**Comment by alexstocker** [comment]
@ibaranov-cp 
Thanx for reporting. I'll have a look asap.

Please provide some log informations from Administration->Settings->General Log Section if possible.

**Comment by ibaranov-cp** [comment]
Found something interesting:
`{"reqId":"CCDcDf6ehTN9dRJ8Pbge","level":3,"time":"2019-02-27T19:57:39+00:00","remoteAddr":"*******","user":"******","app":"PHP","method":"GET","url":"\/owncloud\/apps\/sensorlogger\/","message":"Class 'OCP\\AppFramework\\Db\\QBMapper' not found at \/var\/www\/owncloud\/apps\/sensorlogger\/lib\/Devices.php#15"}`

Perhaps I need to install libqb-dev ?

**Comment by ibaranov-cp** [comment]
Nope, that did not help unfortunately.

**Comment by ibaranov-cp** [comment]
Interesting, this file: https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Db/QBMapper.php

Does not exist on Owncloud. Here are the contents of /var/www/owncloud/lib/public/AppFramework/Db
DoesNotExistException.php  Entity.php  Mapper.php  MultipleObjectsReturnedException.php

Does this mean this app does not work with Owncloud?

**Comment by ibaranov-cp** [comment]
Ha! Copied over the file from the source above, stuck it in the folder listed for owncloud, and it works! 👍

**Comment by alexstocker** [comment]
@ibaranov-cp 
Your report helped me to uncover a problem in the deployment pipeline. Version 0.1.0 for owncloud needs to be revoked, fixed and re-published.
For some strange reasons a wrong version of Devices.php was publish to the marketplace.
Even https://github.com/alexstocker/sensorlogger/blob/0.1.0/lib/Devices.php does not contain this bug. Only the signed, uploaded and published archiv at the marketplace does. That's pretty weird.

**Comment by ibaranov-cp** [comment]
Boo-ya!... Boo-nah?... 
:)
cheers

I might want to write a more minimal Python sensor writing example here :)

**Comment by alexstocker** [comment]
- Bugfix Release [Version 0.1.0.1 published](https://marketplace.owncloud.com/apps/sensorlogger)
- Updated Release Version 0.1.0 revoked

**Comment by alexstocker** [comment]
> Boo-ya!... Boo-nah?...
> :)
> cheers
> 
> I might want to write a more minimal Python sensor writing example here :)

Any contribution welcome!
