### ISSUE TITLE
Support for Nextcloud 16?

### ISSUE THREAD

**Issue by e-alfred** [alexstocker/sensorlogger#81]
Nextcloud 16 was released, can you make a new release supporting it to the App Store?

**Comment by alexstocker** [comment]
@e-alfred 
Thanx for your request. Will release an updated version asap.

**Comment by alexstocker** [comment]
[SensorLogger 0.1.1](https://github.com/alexstocker/sensorlogger/releases/tag/0.1.1nc) for nextcloud released
[apps.nextcloud.com/apps/sensorlogger](https://apps.nextcloud.com/apps/sensorlogger)

Please check it out and let me know if something does not work as expected.

Thanx for your support
