### ISSUE TITLE
[USAGE] simpel step by step howto

### ISSUE THREAD

**Issue by espenbo** [alexstocker/sensorlogger#82]
**Platform you are using**
> owncloud | nextcloud
nextcloud
**Sensors/Hardware**
> Information about the hardware you want to log data from
I have KNX hardware and I use knxd ( https://github.com/knxd/knxd/wiki/KnxTool ) to get the temprature

**Your Goals**
> Tell us what goals you pursue
getting tempratues from the knx to the sensor logger.

I made a simpel bash script to read the temprature.
./TempraturRead.sh 
Sun 9 Jun 14:36:22 CEST 2019
Current Date is: 09-06-2019
Current Time is: 14:36:22
Current stue temp is: 23.0
Current Bad temp is: 24.2
Current GangGulv temp is: 21.6
Current Gang temp is: 24.9
Current Connie temp is: 25.2
Current WalterCo2 temp is: 
Current WalterBryter temp is: 23.7

cat TempraturRead.sh 
#!/bin/bash

rStueTV=`knxtool readtemp ip:localhost 3/0/0`
rBad=`knxtool readtemp ip:localhost 3/0/1`
rGangGulv=`knxtool readtemp ip:localhost 3/0/2`
rGang=`knxtool readtemp ip:localhost 3/0/3`
rConnie=`knxtool readtemp ip:localhost 3/0/4`
rWalterCo2=`knxtool readtemp ip:localhost 3/0/5`
rWalterBryter=`knxtool readtemp ip:localhost 3/0/6`

Year=`date +%Y`
Month=`date +%m`
Day=`date +%d`
Hour=`date +%H`
Minute=`date +%M`
Second=`date +%S`
echo `date`
echo "Current Date is: $Day-$Month-$Year"
echo "Current Time is: $Hour:$Minute:$Second"

knxtool readtemp ip:localhost 3/0/0 > $rStueTV
knxtool readtemp ip:localhost 3/0/1 > $rBad
knxtool readtemp ip:localhost 3/0/2 > $rGangGulv
knxtool readtemp ip:localhost 3/0/3 > $rGang
knxtool readtemp ip:localhost 3/0/4 > $rConnie
knxtool readtemp ip:localhost 3/0/5 > $rWalterCo2
knxtool readtemp ip:localhost 3/0/6 > $rWalterBryter

echo "Current stue temp is: $rStueTV"
echo "Current Bad temp is: $rBad"
echo "Current GangGulv temp is: $rGangGulv"
echo "Current Gang temp is: $rGang"
echo "Current Connie temp is: $rConnie"
echo "Current WalterCo2 temp is: $rWaterCo2"
echo "Current WalterBryter temp is: $rWalterBryter"

**Your Question**
> Please keep your question as short and clear as possible. Thanx
I have tried to understand how to make a new device, and send the temperature to the device fil but I don't under stand it from the wiki or from the examples posted in https://www.html5live.at/2017/03/raspberry-pi-climate-data-logger-using-adafruit-and-a-dht22/

Please, when you have time. Could you make a step by step howto for me/us that is even easier then what you have done before. Maybe use a text file withe two values you get to the sensor device. Or the temperature from the computer from sensors.

sensors
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +61.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:         +53.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:         +61.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:         +60.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:         +53.0°C  (high = +80.0°C, crit = +100.0°C)

Thanks. 
Espen

**Comment by alexstocker** [comment]
Hi @espenbo 

As you can see I'm not that good in writing easy to understand howtos. Sorry.
What you are missing is [register Device](https://github.com/alexstocker/sensorlogger/wiki/API#registerdevice).

```php
{
  "deviceId":"SOME-UNIQUE-DEVICE-IDENTIFIER",
  "deviceName":"Multi Core CPU",
  "deviceType": "CPU Core Temp",
  "deviceGroup": "ISA Adapter",
  "deviceParentGroup": "Server 0",
  "deviceDataTypes": [
    {
      "type": "temperature-core0",
      "description": "Temperature Core 0",
      "unit": "°C"
    },
    {
      "type": "temperature-core1",
      "description": "Temperature Core 1",
      "unit": "°C"
    },
    {
      "type": "temperature-core2",
      "description": "Temperature Core 2",
      "unit": "°C"
    },
    {
      "type": "temperature-core3",
      "description": "Temperature Core 3",
      "unit": "°C"
    }
  ]
}
```
After you have send a register Device request to http://your.nextcloud.instance/index.php/apps/sensorlogger/api/v1/registerdevice/ your will reveive a response like...
```php
{
  "success":true,
  "message":"Device successfully registered",
  "data": [
    {
      "id":"1",
      "description":"Temperature Core 0",
      "type":"temperature-core0",
      "short":"\u00b0C"
    },
    {
      "id":"2",
      "description":"Temperature Core 1",
      "type":"temperature-core1",
      "short":"\u00b0C"
    },
    {
      "id":"3",
      "description":"Temperature Core 2",
      "type":"temperature-core2",
      "short":"\u00b0C"
    },
    {
      "id":"4",
      "description":"Temperature Core 3",
      "type":"temperature-core3",
      "short":"\u00b0C"
    }
  ]
}
```
Now you have registered your device and you are ready to send sensor data to http://your.nextcloud.instance/index.php/apps/sensorlogger/api/v1/createlog/

What you need to take care of are dataType ids.

```php
{
  "date":"2019-06-09 12:30:47",
  "deviceId":"SOME-UNIQUE-DEVICE-IDENTIFIER",
  "data" : [
    {
      "dataTypeId": 1,
      "value": 53.0
    },
    {
      "dataTypeId": 2,
      "value": 61.0
    },
    {
      "dataTypeId": 3,
      "value": 60.0
    },
    {
      "dataTypeId": 4,
      "value": 53.0
    }
  ]
}
```
I hope this helps a little. If you have an further question, please don't hesitate and ask again. As you should now, there a no stupid questions, just stupid answers ;-)

**Comment by espenbo** [comment]
Hello, thanks for helping.

I first made the directories: 
api and v1

So I now have my path:
/var/www/nextcloud/apps/sensorlogger/api/v1
I change the owner of the directory to www-data and group to www-data

I then made the register file in:
/var/www/nextcloud/apps/sensorlogger/api/v1/registerdevice
Then I tride
/var/www/nextcloud/apps/sensorlogger/api/v1/registerdevice.php
and I tride
/var/www/nextcloud/apps/sensorlogger/api/v1/registerdevice/registerdevice
and
/var/www/nextcloud/apps/sensorlogger/api/v1/registerdevice/registerdevice.php

I tride to give the device file and tride that.
/var/www/nextcloud/apps/sensorlogger/api/v1/registerdevice/deviceCPU

The registerdevice file has premision -rw-r--r--

every time I change the place of the file I tried to connect to the web page.
https://Mydomaine.com/index.php/apps/sensorlogger/apps/sensorlogger/api/v1/registerdevice

It just get back to my files section in nextcloud.

questions:
1.
Is the right place to make the registerdevice file:
/var/www/nextcloud/apps/sensorlogger/api/v1/
?

2.
The name off the file. should it be registerdevice or can I call it somthing like deviceCPU, deviceTemp1, deviceTemp2?

3. 
When I have made the file. I open my web browser, connect to my cloud, pick the app sensors. Then past inn:
https://Mydomaine.com/index.php/apps/sensorlogger/apps/sensorlogger/api/v1/registerdevice

I then get a file called /var/www/nextcloud/apps/sensorlogger/api/v1/createlog 
I have one now
/var/www/nextcloud/apps/sensorlogger/api/v1# cat createlog 
{
  "date":"2017-03-03 12:30:47",
  "deviceId":"f7645058-fe8c-11e6-bc64-92361f002671",
  "humidity":34.700000762939,
  "temperature":24
}

4. 
To update the sensors I then write to this file? the createlog file?

I think I have manage to make some good questions, maybe I can help you make a good howto for us that need to have it with teaspoons.

**Comment by alexstocker** [comment]
you have no need to create any directory! The endpoints you need to use, are provided by SensorLogger.

**Comment by alexstocker** [comment]
Please read https://github.com/alexstocker/sensorlogger/wiki/API too.

**Comment by alexstocker** [comment]
@espenbo 
May be this will give you a clue on how to get through. 

```bash
#!/bin/bash
create_log_url="http://owncloud-dev.loc/index.php/apps/sensorlogger/api/v1/createlog/"
register_device_url="http://owncloud-dev.loc/index.php/apps/sensorlogger/api/v1/registerdevice/"
usage="$(basename "$0") [-h] OR [-s] OR [-r] OR [-e] -- demo script to post sensor data and register device to SensorLogger

where:
    -h  show this help text
    -e  post extend sensor data. Register device is mandatory to make use of this.
    -r  register a device with data types"

device_uuid="0002-0655-0000-0000-0000-0002"
user="admin"
token="MFSFF-VREYH-PHSLT-DTMFN"
interval=5

register_device() {
    json_string='{"deviceId":"'${device_uuid}'","deviceDataTypes":[{"type":"cpu-core-temp-0","description":"CoreTemp0","unit":"°C"},{"type":"cpu-core-temp-1","description":"CoreTemp1","unit":"°C"}]}'

    clear
    echo "-- Register a device --"
    curl -k \
    -H "Accept: application/json" \
    -H "Content-Type:application/json" \
    -u ${user}:${token} \
    -X POST -d ${json_string} ${register_device_url}
}

function collect_data {
core_temp0_raw=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input)
core_temp0=$(expr $core_temp0_raw / 1000)

core_temp1_raw=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp4_input)
core_temp1=$(expr $core_temp1_raw / 1000)

json_string='{"deviceId":"'${device_uuid}'","data":[{"dataTypeId":"6","value":"'${core_temp0}'"},{"dataTypeId":"7","value":"'${core_temp1}'"}]}'

curl -k \
-H "Accept: application/json" \
-H "Content-Type:application/json" \
-u ${user}:${token} \
-X POST -d ${json_string} ${create_log_url}
}

create_log_extended() {
    while true; do clear; collect_data; sleep ${interval}; done;
}

#sensors
while getopts "hres" OPTION ; do
  case $OPTION in
    h)
       echo "$usage"
       exit 0
       ;;
    r)
       register_device
       ;;
    e)
       create_log_extended
       ;;
   \?) printf "illegal option: " "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done
```

**Comment by alexstocker** [comment]
@espenbo Hope you have found a solution.
