### ISSUE TITLE
The value 0 isn't accepted

### ISSUE THREAD

**Issue by Kixunil** [alexstocker/sensorlogger#85]
**Describe the bug**
When value 0 is submitted, there's error message "value needs to be an integer or float"

**To Reproduce**
1. Register a device with extended API
2. Submit value 0
3. See error

**Expected behavior**
Value 0 is successfully logged

**Additional context**
I use multiple values, first one is float, second one is int.

**Comment by alexstocker** [comment]
@Kixunil 
Thanx for reporting. Bug confirmed. Will be fixed asap

**Comment by Kixunil** [comment]
I found the solution - see the PR.
