### ISSUE TITLE
BadFunctionCallException: widgetTemplateName does not exist

### ISSUE THREAD

**Issue by Kixunil** [alexstocker/sensorlogger#86]
**Describe the bug**
The app crashes with this message: BadFunctionCallException: widgetTemplateName does not exist

sensorlogger/templates/widget_dashboard.php line 114

**To Reproduce**
1. Go to dashboard
2. Add a widget
3. See the widget disappear
4. Refresh the page
5. Page reports error, look at logs

**Expected behavior**
No crash

**Additional context**
I looked at the code and the method is indeed called but I don't see it defined anywhere.

**Comment by alexstocker** [comment]
Thanx for reporting. This sounds like a seriouse bug. Which NC Version are you using?

**Comment by Kixunil** [comment]
I use the latest NC (installed few days ago) and sensorlogger from its store I picked the "Chart" widget.

For the time being, I solved it by commenting out the `else` branch executed by that code in the aforementioned file. It worked for a while but now it doesn't show data anymore (but maybe because I'm logging every 5 in and that's too much?)

**Comment by alexstocker** [comment]
Fixed with https://github.com/alexstocker/sensorlogger/releases/tag/0.1.2nc. Available for download https://apps.nextcloud.com/apps/sensorlogger
