### ISSUE TITLE
Support for Nextcloud 17?

### ISSUE THREAD

**Issue by e-alfred** [alexstocker/sensorlogger#89]
Hello,

can you create a new release for Nextcloud 17? It would be highly appreciated!

**Comment by alexstocker** [comment]
Hi @e-alfred 
Thanx for your request.
I'll do my best to release a NC17 compatible SensorLogger version soon.

**Comment by alexstocker** [comment]
Fixed with https://github.com/alexstocker/sensorlogger/releases/tag/0.1.2nc. Available for download https://apps.nextcloud.com/apps/sensorlogger
