### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Seren200018** [alexstocker/sensorlogger#91]
**Describe the bug**
When trying to install, the error message "An exception occurred while executing 'CREATE UNIQUE INDEX sensorlogger_devices_unique_idx ON oc_sensorlogger_devices (user_id, uuid)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes" pops up. Addon can not be installed.

**To Reproduce**
Press Install on Apps Tab
**Expected behavior**
Installation successfull

Nextcloud Version 18.0.1
OS: Debian Stretch

**Comment by alexstocker** [comment]
Hi @Seren200018 
Thanx for reporting. I will investigate this error as soon as possible. 
My first guess and google result points to an database related issue. Please have a look at https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740

kindest
Alex

**Comment by Seren200018** [comment]
@alexstocker that resolved the issue
