### ISSUE TITLE
Error Installing on Nextcloud 18 - seemed to work on another instance of Nextcloud 18

### ISSUE THREAD

**Issue by aaxios1** [alexstocker/sensorlogger#92]
## Expected Behavior
Install successfully

## Actual Behavior
An error occured during the request. Unable to proceed.
App "Sensorlogger" cannot be installed because the following dependencies are not fulfilled: Following databases are supported: Array, mysql

## Steps to Reproduce the Problem

  1. Add from App store of Nextcloud 18
  1.
  1.

## Specifications

  - Version: 18.01
  - Platform:  Ubuntu 18.04
  - Subsystem:

**Comment by alexstocker** [comment]
@aaxios1 Thanx for reporting. I'll have a look at it as soon as possible.
