### ISSUE TITLE
Docker Error:databases are supported: Array, mysql

### ISSUE THREAD

**Issue by ilsicca** [alexstocker/sensorlogger#93]
## Expected Behavior
An error occured during the request. Unable to proceed.
App "Sensorlogger" cannot be installed because the following dependencies are not fulfilled: Following databases are supported: Array, mysql
## Steps to Reproduce the Problem

  1.Add from App store of Nextcloud 18 on Docker
  1.
  1.

## Specifications

  - Version: Nextcloud 18.0.1
  - Platform: Debian Buster
  - Subsystem: Docker version 19.03.7

**Comment by alexstocker** [comment]
@ilsicca Thanx for reporting. Maybe mysql ist missing within your docker container.
