### ISSUE TITLE
App not working when link to php.ini is present in app directory

### ISSUE THREAD

**Issue by berho** [alexstocker/sensorlogger#94]
**Describe the bug**
To set parameters on shared hosting I have to place a link to php.ini in every directory where php files reside.
Sensorlogger does show the content of the file on top of site but sensorlogger does not work.

**To Reproduce**
1. place link to php.ini in directories:
```
ln -s path_to/php.ini nextcloud/apps/sensorlogger/appinfo/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/controller/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/lib/Migration/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/lib/Utils/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/lib/Widgets/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/lib/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/templates/widgets/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/templates/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/tests/curl/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/tests/integration/
ln -s path_to/php.ini nextcloud/apps/sensorlogger/tests/
```
2. try sensorlogger

**Expected behavior**
sensorlogger work as expected

**Comment by alexstocker** [comment]
@berho there ist, for sure, no need to add or link php.ini  to any subdirectory. 
Sorry, but I can not provide any further help in this topic.
