### ISSUE TITLE
[USAGE] Device request registration failed

### ISSUE THREAD

**Issue by catamold** [alexstocker/sensorlogger#96]
**Platform you are using**
owncloud

**Sensors/Hardware**
I use Raspberry Pi core temperature data

**Your Goals**
I've read the Wiki documentation and past issues. To be honest, the documentation is not very clear, there are missing pieces of information, but anyway I am hosting a local owncloud server on Raspberry Pi, so the URL of the web page is an IP address.

I installed SensorLogger from owncloud market and now I want to monitor core temperature of the Raspberry Pi. I looked up on internet to get the core temperature of Pi and I found the followig command:

`vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*'`

This is an example of the result: `49.4`

Good, now I want to make it available on owncloud server, so I'll have to register the device using a POST request. On Security page of the owncloud I also created an App password / token. That was the username: `talina` and pasword/token: `DKYYH-KKHUR-HZDXM-JFASK`

First of all I want to describe my current folders on Pi:
The owncloud path is `/var/www/nextcloud/`. In addition to certain files, there's **index.php**, **apps** and **apps-external** directories. In **apps** there's no _sensorlogger_ folder, but it can be found in **apps-external**. The **sensorlogger** directory doesn't have any _api_  folder, but as I followed some Issues responses, there's no need to be and neither do I have to create any files or dirs.

Now it's time to create the POST request to register my device. Well, i run the following command on Terminal and the response wasn't ok:
```
curl -k \
     -H "Accept: application/json" \
     -H "Content-Type:application/json" \
     -u talina:DKYYH-KKHUR-HZDXM-JFASK \
     -X POST -d {"deviceId":"0002-0655-0000-0000-0000-0001","deviceName":"Pi_Temperature","deviceType": "Raspberry_Pi_3B","deviceGroup":"Raspberry","deviceParentGroup":"Server 0","deviceDataTypes":[{"type":"cpu-core-temp","description":"CoreTemp","unit":"°C"}]} http://192.168.1.25/index.php/apps/sensorlogger/api/v1/registerdevice/
```
I put a random id to _deviceId_ and some stuff to _deviceName_, _deviceType_, _deviceGroup_ and _deviceParentGroup_. And this was the response:
```
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: POST
curl: (3) bad range in URL position 83:
Raspberry_Pi_3B,deviceGroup:Raspberry,deviceParentGroup:Server 0,deviceDataTypes:[type:cpu-core-temp]}
                                                                                  ^
curl: (3) unmatched close brace/bracket in URL position 82:
Raspberry_Pi_3B,deviceGroup:Raspberry,deviceParentGroup:Server 0,deviceDataTypes:[description:CoreTemp]}
                                                                                 ^
curl: (3) bad range in URL position 83:
Raspberry_Pi_3B,deviceGroup:Raspberry,deviceParentGroup:Server 0,deviceDataTypes:[unit:°C]}
                                                                                  ^
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

**Your Question**
What am I missing or what am I doing wrong?

I checked the URL to `http://192.168.1.25/index.php/apps/sensorlogger/` on browser and it works, it takes me to SensorLogger page of owncloud. The dashboard widget has no devices and I know it won't be something, because the POST request failed.

Thanks,
Catalin

**Comment by alexstocker** [comment]
HI @catamold 

Well, try this
`
curl -k -v -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json"  -H "Content-Type:application/json"  -X POST -d '{"deviceId":"0002-0655-0000-0000-0000-0001","deviceName":"Pi_Temperature","deviceType":"Raspberry_Pi_3B","deviceGroup":"Raspberry","deviceParentGroup":"Server 0","deviceDataTypes":[{"type":"cpu-core-temp","description":"CoreTemp","unit":"°C"}]}' http://192.168.1.25/index.php/apps/sensorlogger/
`
- -v ... use verbose output to get more information about the curl request
- BasicAuth is required by owncloud|nextcloud
- single ' quote marks required otherwise [globbing] bad range in column happens
- please never expose real usernames, passwords or tokens even from local environments

Success Response
`
{"success":true,"message":"Device successfully registered","data":[{"id":"15","description":"CoreTemp","type":"cpu-core-temp","short":"\u00b0C"}]}
`

Error Response
`
{"success":false,"error":{"code":9002,"message":"Device already exists!"}} or just nothing if curl failed for some unknown reason and -v is not used
`

**Comment by catamold** [comment]
Hello @alexstocker, thanks for your quick response.

The username and token are not real, they are random used just for showing the steps performed. No worries. I will use the same user and password in the next situation.

I run the command adapted by you and it doesn't work, I don't receive a response, so I made some changes:
- I changed the owncloud URL server to **https**
- I changed the URL to the complete location (+ **../api/v1/registerdevice/**)
- There's no need for `-X POST` in the commnand as _Note: Unnecessary use of -X or --request, POST is already inferred._

Here is the command updated:
`
curl -k -v -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json" -H "Content-Type:application/json" -d '{"deviceId":"0002-0655-0000-0000-0000-0001","deviceName":"Pi_Temperature","deviceType":"Raspberry_Pi_3B","deviceGroup":"Raspberry","deviceParentGroup":"Server 0","deviceDataTypes":[{"type":"cpu-core-temp","description":"CoreTemp","unit":"°C"}]}' https://192.168.1.25/index.php/apps/sensorlogger/api/v1/registerdevice/
`

Now all's good, I logged in my ownCloud account, then I successfully added the *Pi_Temperature* widget chart on SensorLoger page. Thanks a lot.

Of course I don't see any data, so moving on to the next step. I have to add data temperature, so that I see the data on chart. I'm looking on **createLog** section. I will create a POST request, in which I'll pass the temperature of the Pi system, but for now it will be just a random number, not the linux command, which I've written in the current issue. For the request, I have to pass the **deviceId** and **cpu-core-temp**, the one I've mentioned in _deviceDataTypes_ from _registerdevice_ request. This is the request:
`
curl -k -v -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json" -H "Content-Type:application/json" -d '{"deviceId":"0002-0655-0000-0000-0000-0001","cpu-core-temp":45}' https://192.168.1.25/index.php/apps/sensorlogger/api/v1/createlog/
`


The response is unsuccessful, I blurred some data response with _[sensible_information]/[si]_:
```
* Expire in 0 ms for 6 (transfer 0x91f880)
*   Trying 192.168.1.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x91f880)
* Connected to 192.168.1.25 (192.168.1.25) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=[sensible_information]; ST=[si]; L=[si]; O=[si]; OU=[si]; CN=[si]; emailAddress=[si]
*  start date: Sep 24 20:53:30 2020 GMT
*  expire date: Sep 24 20:53:30 2022 GMT
*  issuer: C=[sensible_information]; ST=[si]; L=[si]; O=[si]; OU=[si]; CN=[si]; emailAddress=[si]
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x91f880)
> POST /index.php/apps/sensorlogger/api/v1/createlog/ HTTP/2
> Host: 192.168.1.25
> User-Agent: curl/7.64.0
> Authorization: Basic Y2F0YWxpbjpBSVFYTi1HV1RaWi1GQ1RETS1YQUZRVQ==
> Accept: application/json
> Content-Type:application/json
> Content-Length: 63
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 200
< server: nginx/1.14.2
< date: Mon, 28 Sep 2020 18:08:06 GMT
< content-type: application/json; charset=utf-8
< content-length: 95
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< pragma: no-cache
< set-cookie: oc_sessionPassphrase=piTe6Neg1bJRbIkjHqZRIRcZa2lCLRVZm55MSFGQEVLL%2FUF3I7HRcv6PmIjlEbH63OC8iwG8Rp6CPDM1qgiajNIjfB1X2B3v2NHfjVyoqLup7wHaDw6zL%2BC7jfeOhSRY; path=/; secure; HttpOnly; SameSite=strict
< set-cookie: ocs1cdia9m5g=bvktl6276lr8jv31goh12fe0ju; path=/; secure; HttpOnly
< cache-control: no-cache, no-store, must-revalidate
< content-security-policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self' data:
< strict-transport-security: max-age=15552000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-robots-tag: none
< x-download-options: noopen
< x-permitted-cross-domain-policies: none
<
* Connection #0 to host 192.168.1.25 left intact
{"success":false,"error":{"code":9001,"message":"Neither temperature nor humidity data found"}}
```

The **9001** code means missing parameters, what am I missing? Also, I don't understand the message, I am not passing any humidity data, just the temperature.

I also tried to get the device dataType using the following GET request:
`
curl -k -v -i -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json" -H "Content-Type: application/json" -X GET -d '{"deviceId":"0002-0655-0000-0000-0000-0001"}' https://192.168.1.25/index.php/apps/sensorlogger/api/v1/getdevicedatatypes/
`

The problem here is that I don't receive any response, so I think that I'm missing something here as well:

```
* Expire in 0 ms for 6 (transfer 0xf52880)
*   Trying 192.168.1.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0xf52880)
* Connected to 192.168.1.25 (192.168.1.25) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=[sensible_information]; ST=[si]; L=[si]; O=[si]; OU=[si]; CN=[si]; emailAddress=[si]
*  start date: Sep 24 20:53:30 2020 GMT
*  expire date: Sep 24 20:53:30 2022 GMT
*  issuer: C=[sensible_information]; ST=[si]; L=[si]; O=[si]; OU=[si]; CN=[si]; emailAddress=[si]
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xf52880)
> GET /index.php/apps/sensorlogger/api/v1/getdevicedatatypes/ HTTP/2
> Host: 192.168.1.25
> User-Agent: curl/7.64.0
> Authorization: Basic Y2F0YWxpbjpBSVFYTi1HV1RaWi1GQ1RETS1YQUZRVQ==
> Accept: application/json
> Content-Type: application/json
> Content-Length: 44
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 405
HTTP/2 405
< server: nginx/1.14.2
server: nginx/1.14.2
< date: Mon, 28 Sep 2020 18:18:07 GMT
date: Mon, 28 Sep 2020 18:18:07 GMT
< content-type: text/html; charset=UTF-8
content-type: text/html; charset=UTF-8
< set-cookie: ocs1cdia9m5g=fkchoa4ue460c0l8o2ltsi29g8; path=/; secure; HttpOnly
set-cookie: ocs1cdia9m5g=fkchoa4ue460c0l8o2ltsi29g8; path=/; secure; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
pragma: no-cache
< set-cookie: oc_sessionPassphrase=9hFoxbAfg6NAKijQKbD9TV0rukbXGfOh4RSgKuDT3UlzSf0PhEiEj%2Fo32H%2BfRGU4zengaDylk6Xeyra7AwqCUyW%2FfklBUgklEYB0PM28Yo2pxbNPKpkTcYcpTSSjx3%2Fk; path=/; secure; HttpOnly; SameSite=strict
set-cookie: oc_sessionPassphrase=9hFoxbAfg6NAKijQKbD9TV0rukbXGfOh4RSgKuDT3UlzSf0PhEiEj%2Fo32H%2BfRGU4zengaDylk6Xeyra7AwqCUyW%2FfklBUgklEYB0PM28Yo2pxbNPKpkTcYcpTSSjx3%2Fk; path=/; secure; HttpOnly; SameSite=strict
< content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
< strict-transport-security: max-age=15552000; includeSubDomains; preload
strict-transport-security: max-age=15552000; includeSubDomains; preload

<
* Connection #0 to host 192.168.1.25 left intact
```

**Comment by alexstocker** [comment]
[/api/v1/getdevicedatatypes/](https://github.com/alexstocker/sensorlogger/wiki/API#getdevicedatatypes)
`
curl -k -v  -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json"  -H "Content-Type:application/json"  -X POST -d '{"deviceId":"0002-0655-0000-0000-0000-0001"}' https://192.168.1.25/index.php/apps/sensorlogger/api/v1/getdevicedatatypes/
`

Should **Response** something like
`
{"success":true,"message":"DataTypes for Device #0002-0655-0000-0000-0000-0001","data":[{"id":"15","description":"CoreTemp","type":"cpu-core-temp","short":"\u00b0C"}]}
`

[Extended Createlog](https://github.com/alexstocker/sensorlogger/wiki/API#extended) would look like
`
curl -k -v  -H "Authorization: Basic $(echo -n talina:DKYYH-KKHUR-HZDXM-JFASK | base64)" -H "Accept: application/json"  -H "Content-Type:application/json"  -X POST -d '{"date":"2020-09-30 12:30:47","deviceId":"0002-0655-0000-0000-0000-0001","data" : [{"dataTypeId": 15,"value": 55.2}]}' https://192.168.1.25/index.php/apps/sensorlogger/api/v1/createlog/
`

**Comment by catamold** [comment]
It's working. Thank you @alexstocker for all your help and time.

**Comment by alexstocker** [comment]
My pleasure!
