### ISSUE TITLE
Improve description at Nextcloud App Store

### ISSUE THREAD

**Issue by rakekniven** [alexstocker/sensorlogger#98]
**Describe the bug**
Currently the description ist "SensorLogger for ownCloud enables users to log data provided by sensor devices".

That is very short and does not contain the word Nextcloud.

**Expected behavior**
Add word Nextcloud.
Add some more details about what kind of sensors are supported and so on.

Thank you

**Comment by alexstocker** [comment]
@rakekniven Thanx for the hint. You may do may change this in https://github.com/alexstocker/sensorlogger/blob/0.1-nc-devel/appinfo/info.xml#L5 on your own and create a pull request if you want to.

Any contribution warmly welcome!
